"""empty message

Revision ID: 058be477fd30
Revises: 9ce30f17f52a
Create Date: 2021-02-20 20:36:31.580464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '058be477fd30'
down_revision = '9ce30f17f52a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('free', sa.Column('ford', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('free', 'ford')
    # ### end Alembic commands ###
