"""empty message

Revision ID: 4f2c04644882
Revises: a52abeb6415b
Create Date: 2021-02-12 09:45:40.258383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f2c04644882'
down_revision = 'a52abeb6415b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('presonid', sa.VARCHAR(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'presonid')
    # ### end Alembic commands ###
