"""empty message

Revision ID: 7ac547e71ab3
Revises: 058be477fd30
Create Date: 2021-02-22 21:32:59.154556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ac547e71ab3'
down_revision = '058be477fd30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu', sa.Column('mord', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('menu', 'mord')
    # ### end Alembic commands ###
