"""empty message

Revision ID: aad0971360cb
Revises: 4f2c04644882
Create Date: 2021-02-15 20:24:40.957459

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'aad0971360cb'
down_revision = '4f2c04644882'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu', sa.Column('isuse', sa.CHAR(length=1), nullable=False))
    op.drop_column('menutem', 'isuse')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menutem', sa.Column('isuse', mysql.CHAR(length=1), nullable=False))
    op.drop_column('menu', 'isuse')
    # ### end Alembic commands ###
