"""empty message

Revision ID: bdc66659637c
Revises: 7ac547e71ab3
Create Date: 2021-02-22 21:35:45.964140

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bdc66659637c'
down_revision = '7ac547e71ab3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('menu', 'mord')
    op.add_column('menutem', sa.Column('mord', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('menutem', 'mord')
    op.add_column('menu', sa.Column('mord', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
